# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de270e5eda642f8931ec8c0c4ff1d18339c2937fb3f680ab61943de60a7c83b5701d1188581ee1be55e348e1eec52c778a3967abab4699e91e965b5a4d8786f6

test:
  secret_key_base: 28e9dab179f28542112a7d1789e3a3a15b6b2f9a5dc69a307ad9c3bb6bd380cccbb9ca6ce4723e915fa635e97d8ee756e041cf9915a92a5444f363deb43f8928

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
